---
title: "Bootstrap Analyses"
author: "Raymond Lee"
date: "2023-12-04"
output: html_document
---


```{r setup}
knitr::opts_knit$set(root.dir = 'C:/Users/explorer/Documents/Classes/SDS625/ACTE')
```


```{r}
library(dplyr)
library(tidyverse)
library(splines)
# source("Code/2_X_learner.R")

# packages for 2_X_learner.R
library(Rforestry)
library(ggplot2)
library(dplyr)
library(splines)
library(reshape2)
library(lme4)
library(tidyverse)
library(pubtheme)
source("Code/X_RF_OLS.R")

# for multi-core use
library(doParallel)
library(foreach)

packages_needed <- c("dplyr", "tidyverse", "splines", "Rforestry", "dplyr", "reshape2", "lme4")

source("Code/bootstrap_utilities.R")
```


# set bootstrap hyperparameters
```{r}
parameters <- c("p100", "a100", "r100")

# complete possible stats to predict:
# "net.rat", "off.rat", "def.rat", "p100", "a100", "r100", "s100", 
#            "b100", "to100", "fgp", "oreb.p", "dreb.p", "ts.p",
#            "or100", "dr100", 'fg3p')

min_per_player <- 25
num_games_together <- 10

n_boots <- 100
boot_size <- 1000
year <- 2022
```


# run the bootstrapping process using multicore
```{r}

#load data
r_df <- readRDS("data/1_Cleaned_df.rds")
# b2b_df <- readRDS("data/1_Cleaned_dfB2B.rds")

# create list pair-player information
pairs_df <- get_pairs_names(r_df, min_per_player, num_games_together)

#run the bootstrap
curryear_pairs <- pairs_df[pairs_df$season == year,]

my_results <- initiate_bootstrap(curryear_pairs,
                                 r_df, n_boots, boot_size,
                                 yvars=parameters,
                                 ncores=5)

saveRDS(my_results, paste("Data/boot/n", n_boots, "_k", boot_size, "bootstraps.RDS"))
```

# Visualize the distributions of ages selected
```{r}
pairs_ages <- pairs_df %>% pivot_longer(cols=starts_with("pid"), names_to="order", values_to="pid")
pairs_ages <- merge(pairs_ages[c("gid", "pid")], r_df[, c("gid", "pid", "age")], by=c("gid", "pid"))

hist(pairs_ages$age, col="skyblue", xlab="Ages", main="Ages in Pairs")
```

# Create Graphs, k=100
```{r}
n <- 100
boot_results_k100 <- readRDS("Data/boot/n100_k100_pts-reb-ast_bootstraps.RDS")

boot_summaries <- boot_results_k100[boot_results_k100$boot_idx <= n,] %>% group_by(stat_variable, age) %>%
  summarize(
    mean = mean(value),
    sd = sd(value),
    ci95_lower = quantile(value, 0.025),
    ci95_upper = quantile(value, 0.975)
  )

scale_sd <- 1

ggplot(boot_summaries, aes(x = age, y = mean, group = stat_variable, color = stat_variable)) +
  geom_line(size=1.3) +
  geom_ribbon(aes(ymin = mean - scale_sd*sd, ymax = mean + scale_sd*sd, fill = stat_variable), alpha = 0.2) +
  labs(title = paste("n = ", n, ", k = ", 100),
       x = "Age", y = "Mean Value") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 25),  # Adjust title text size
    axis.title.x = element_text(size = 25), # Adjust x-axis label size
    axis.title.y = element_text(size = 25)
  ) + 
  guides(color = guide_legend(title = "Variables"), fill = guide_legend(title = "Variables")) + 
  ylim(-6, 6)
```

# Create Graphs, k=500
```{r}
n <- 100
boot_results_k500 <- readRDS("Data/boot/n100_k500_pts-reb-ast_bootstraps.RDS")

boot_summaries <- boot_results_k500[boot_results_k500$boot_idx <= n,] %>% group_by(stat_variable, age) %>%
  summarize(
    mean = mean(value),
    sd = sd(value),
    ci95_lower = quantile(value, 0.025),
    ci95_upper = quantile(value, 0.975)
  )

scale_sd <- 1

ggplot(boot_summaries, aes(x = age, y = mean, group = stat_variable, color = stat_variable)) +
  geom_line(size=1.3) +
  geom_ribbon(aes(ymin = mean - scale_sd*sd, ymax = mean + scale_sd*sd, fill = stat_variable), alpha = 0.2) +
  labs(title = paste("n = ", n, ", k = ", 500),
       x = "Age", y = "Mean Value") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 25),  # Adjust title text size
    axis.title.x = element_text(size = 25), # Adjust x-axis label size
    axis.title.y = element_text(size = 25)
  ) + 
  guides(color = guide_legend(title = "Variables"), fill = guide_legend(title = "Variables")) + 
  ylim(-6, 6)
```

# Create Graphs, k=1000
```{r}
n <- 100
boot_results_k1000 <- readRDS("Data/boot/n100_k1000_pts-reb-ast_bootstraps.RDS")

boot_summaries <- boot_results_k1000[boot_results_k1000$boot_idx <= n,] %>% group_by(stat_variable, age) %>%
  summarize(
    mean = mean(value),
    sd = sd(value),
    ci95_lower = quantile(value, 0.025),
    ci95_upper = quantile(value, 0.975)
  )

scale_sd <- 1

ggplot(boot_summaries, aes(x = age, y = mean, group = stat_variable, color = stat_variable)) +
  geom_line(size=1.3) +
  geom_ribbon(aes(ymin = mean - scale_sd*sd, ymax = mean + scale_sd*sd, fill = stat_variable), alpha = 0.2) +
  labs(title = paste("n = ", n, ", k = ", 1000),
       x = "Age", y = "Mean Value") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 25),  # Adjust title text size
    axis.title.x = element_text(size = 25), # Adjust x-axis label size
    axis.title.y = element_text(size = 25)
  ) + 
  guides(color = guide_legend(title = "Variables"), fill = guide_legend(title = "Variables")) + 
  ylim(-6, 6)
```



